version: '3'
services:
  #Server
  server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    environment:
      PORT: 3001
    #Client
  client:
    build: ./client
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      REACT_APP_API_URL: http://127.0.0.1:3001
